-- 

CREATE TABLE CURSOS(
CODIGO NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(100) NOT NULL

);


CREATE TABLE ALUMNOS(
COD_ALUMNO NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(100) NOT NULL,
APELLIDO VARCHAR2(100) NOT NULL,
COD_CURSO NUMBER REFERENCES CURSOS(CODIGO)
);

INSERT INTO CURSOS VALUES(1,'WEB');
INSERT INTO ALUMNOS VALUES(100,'RAUL','PEREZ',1);


CREATE TABLE ALUMNOS1(
COD_ALUMNO NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(100) NOT NULL,
APELLIDO VARCHAR2(100) NOT NULL,
COD_CURSO NUMBER,
CONSTRAINT CURSO_ALUMNO FOREIGN KEY (COD_CURSO) REFERENCES CURSOS(CODIGO)
);


CREATE TABLE EMPLEADO(
CODIGO NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(100) NOT NULL,
SALARIO NUMBER CHECK (SALARIO > 1000)
);


INSERT INTO EMPLEADO VALUES(1,'ALBERTO',900);


CREATE TABLE EMPLEADOS1(
CODIGO NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(100) NOT NULL CHECK (NOMBRE = UPPER(NOMBRE)),
SALARIO NUMBER CHECK (SALARIO > 1000)
);

INSERT INTO EMPLEADO VALUES(1,'ALBERTO',1900);

