CREATE TABLE DEPT2
(CODIGO NUMBER,
NOMBRE VARCHAR2(100),
JEFE NUMBER
);

INSERT INTO DEPT2 VALUES (1,UPPER('informatica'),100); 

INSERT INTO DEPT2 (CODIGO,NOMBRE,JEFE)
                  SELECT DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID FROM DEPARTMENTS
                  WHERE LOCATION_ID=1700;
                  

                  
                  