CREATE SEQUENCE SECUENCIA1 INCREMENT BY 1
MAXVALUE 1000 MINVALUE 20 CACHE 20;


SELECT SECUENCIA1.NEXTVAL FROM DUAL;


SELECT SECUENCIA1.CURRVAL FROM DUAL;



INSERT INTO REGIONS1 VALUES(SECUENCIA1.NEXTVAL,'AAAA');
SELECT * FROM REGIONS1;

DROP SEQUENCE SECUENCIA1;