
CREATE TABLE EMPLEADOS
AS SELECT * FROM employees;


CREATE TABLE EMPLEADOS_50
AS SELECT * FROM employees WHERE department_id = 50;


CREATE TABLE EMPLEADO2 
AS SELECT FIRST_NAME || '  ' || LAST_NAME AS NOMBRE, SALARY AS SALARIO, SALARY * 12 AS NETO
FROM employees;
