DROP TABLE NOM_EMPLES;
DROP TABLE SALARIOS;

CREATE TABLE NOM_EMPLES (COD_EMPLE NUMBER, FIRST_NAME VARCHAR2(100));

CREATE TABLE SALARIOS (COD_EMPLE NUMBER, SALARY NUMBER);

INSERT ALL
   INTO NOM_EMPLES VALUES (EMPLOYEE_ID,FIRST_NAME)
   INTO SALARIOS VALUES (EMPLOYEE_ID,SALARY)
SELECT * FROM EMPLOYEES;

SELECT * FROM NOM_EMPLES;
SELECT * FROM SALARIOS;



INSERT ALL
   INTO NOM_EMPLES VALUES (1,'HOLA')
   INTO SALARIOS VALUES (1,100)
SELECT 1 FROM DUAL;

