

SELECT DATOS FROM PRODUCTOS1;

UPDATE PRODUCTOS1 SET DATOS= JSON_TRANSFORM(DATOS, SET '$.POBLACION' = 90000);

UPDATE PRODUCTOS1 SET DATOS= JSON_TRANSFORM(DATOS, SET '$.POBLACION' = 190000) WHERE CODIGO = 1;


-- 9.1
SELECT DATOS FROM PRODUCTOS1;
SELECT JSON_TRANSFORM(DATOS, SET '$.POBLACION' = 1000) FROM PRODUCTOS1 WHERE CODIGO = 1;

SELECT DATOS FROM PRODUCTOS1;
SELECT JSON_TRANSFORM(DATOS, INSERT '$.TIPO'='TIPO1') FROM PRODUCTOS1 WHERE CODIGO = 1;
SELECT JSON_TRANSFORM(DATOS, APPEND '$.TELEFONOS'='999999') FROM PRODUCTOS1 WHERE CODIGO = 3;


SELECT JSON_TRANSFORM(DATOS, RENAME '$.POBLACION' = 'POB') FROM PRODUCTOS1 WHERE CODIGO = 1;

SELECT JSON_TRANSFORM(DATOS, REPLACE '$.POBLACION' = 1000) FROM PRODUCTOS1 WHERE CODIGO = 1;

SELECT JSON_TRANSFORM(DATOS, REMOVE '$.POBLACION') FROM PRODUCTOS1 WHERE CODIGO = 1;

SELECT JSON_TRANSFORM(DATOS, KEEP '$.DIRECCION.CALLE') FROM PRODUCTOS1 WHERE CODIGO = 3;
