--1)
CREATE TABLE PAISES
(
COD_PAIS NUMBER NOT NULL PRIMARY KEY
, NOMBRE VARCHAR2(100) NOT NULL CHECK (NOMBRE=UPPER(NOMBRE))
);

--2)
CREATE TABLE "HR"."CIUDADES"
( "COD_CIUDAD" NUMBER PRIMARY KEY,
"NOMBRE" VARCHAR2(100) CHECK (NOMBRE=UPPER(NOMBRE)),
"POBLACION" NUMBER CHECK (POBLACION>0),
"COD_PAIS" NUMBER REFERENCES PAISES(COD_PAIS));

--3 )
INSERT INTO PAISES VALUES(18,'ESTADOS UNIDOS');
SELECT * FROM PAISES;

-- 4)
INSERT INTO PAISES VALUES(19,'francia');

-- 5)
INSERT INTO PAISES VALUES(19,'FRANCIA');
SELECT * FROM PAISES;

--6)
INSERT INTO CIUDADES VALUES (1,'NUEVA YORK',4000000,18);
SELECT * FROM CIUDADES;

--7)
INSERT INTO CIUDADES VALUES (1,'ROMA',3000000,40);

-- 8)
INSERT INTO PAISES VALUES(40,'ITALIA');
SELECT * FROM PAISES;

--9)
INSERT INTO CIUDADES VALUES (2,'venecia',1000000,40);

-- 10)
INSERT INTO CIUDADES VALUES (3,'TURIN',0,40);

-- 11)
INSERT INTO CIUDADES VALUES (2,'VENECIA',1000000,40);
INSERT INTO CIUDADES VALUES (3,'TURIN',1200000,40);
INSERT INTO CIUDADES VALUES (4,'BOSTON',1500000,18);
INSERT INTO CIUDADES VALUES (5,'PARÍS',5000000,19);
INSERT INTO CIUDADES VALUES (6,'CHICAGO',3000000,40);

SELECT * FROM ciudades;

-- 12)
CREATE TABLE CIUDADES_PEQUE AS SELECT * FROM CIUDADES WHERE POBLACION <2000000;
SELECT * FROM CIUDADES_PEQUE;

--13)
ALTER TABLE CIUDADES_PEQUE ADD CONSTRAINT PK1 PRIMARY KEY(COD_CIUDAD);


-- 14(
ALTER TABLE CIUDADES_PEQUE ADD BANDERA VARCHAR2(100);
DESC CIUDADES_PEQUE;

-- 15)
INSERT INTO CIUDADES_PEQUE VALUES (7,'MARSELLA',900000,19,'BANDERA FRANCESA');
SELECT * FROM CIUDADES_PEQUE;

--16)
ALTER TABLE CIUDADES_PEQUE DROP COLUMN BANDERA;
DESC CIUDADES_PEQUE;

-- 17)
DROP TABLE CIUDADES_PEQUE;