--CREAR LAS TABLAS
CREATE TABLE COCHES1
(
CODIGO NUMBER,
NOMBRE VARCHAR2(100));

CREATE TABLE COCHES2
(
CODE NUMBER,
NAME VARCHAR2(100));

--INSERTAR DATOS EN TABLAS
INSERT INTO COCHES1 VALUES(1,'BMW 3');
INSERT INTO COCHES1 VALUES(2,'AUDI A5');
INSERT INTO COCHES1 VALUES(3,'CITROEN C5');
INSERT INTO COCHES1 VALUES(4,'RENAULT CLIO');
INSERT INTO COCHES2 VALUES(1,'BMW 3');
INSERT INTO COCHES2 VALUES(6,'MERCEDES C');
INSERT INTO COCHES2 VALUES(3,'CITROEN C5');
INSERT INTO COCHES2 VALUES(7,'FORD MUSTANG');
COMMIT;


--UNION 
 SELECT Codigo,Nombre FROM coches1
 UNION
 SELECT Code,Name FROM coches2;
 
 --UNION ALL
 SELECT Codigo,Nombre FROM coches1
 UNION ALL
 SELECT Code,Name FROM coches2;
 
 -- INTERSECT
  SELECT Codigo,Nombre FROM coches1
 INTERSECT
 SELECT Code,Name FROM coches2;
 
  -- MINUS
  SELECT Codigo,Nombre FROM coches1
 MINUS
 SELECT Code,Name FROM coches2;
 