CREATE TABLE EJERCICIO1(
COD_MATRICULA NUMBER,
NOMBRE VARCHAR2(20 BYTE),
APELLIDO1 VARCHAR2(20 BYTE),
APELLIDO2 VARCHAR2(20 BYTE),
EDADI           NUMBER,
FECHA_MATRICULA DATE
);

DESC EJERCICIO1;

CREATE TABLE CENTROS(
CODIGO_CENTRO NUMBER,
NOMBRE VARCHAR2(100),
PROVINCIA VARCHAR2(100) DEFAULT 'MADRID',
FECHA_ALTA DATE DEFAULT SYSDATE,
NUM_ALUMNOS NUMBER DEFAULT 0
);

DESC CENTROS;

INSERT INTO CENTROS (CODIGO_CENTRO,NOMBRE) VALUES(1,'MATEMÁTICAS');
SELECT * FROM CENTROS;

CREATE TABLE CURSOS
(
COD_CURSO NUMBER PRIMARY KEY
, NOMBRE_CURSO VARCHAR2(50) NOT NULL UNIQUE
, RESPONSABLE VARCHAR2(20)
);

DESC CURSOS;

--Correcto
INSERT INTO CURSOS VALUES (1,'FISICA','JUANP');

--incorrecto
INSERT INTO CURSOS VALUES (1,'LITERATURA','JUANP');

