-- INLINE VIEWS

CREATE VIEW VISTA_EMPLE AS SELECT * FROM employees ORDER BY salary DESC;

SELECT * fROM VISTA_EMPLE WHERE SALARY > 5000;


SELECT FIRST_NAME, SALARY FROM (

SELECT * FROM employees ORDER BY SALARY DESC
);


CREATE TABLE REGIONES1 AS SELECT * FROM REGIONS;

SELECT * FROM REGIONES1;

CREATE VIEW VIEW_REGIONES AS SELECT * FROM REGIONES1;

INSERT INTO VIEW_REGIONES VALUES(5,'ANTARTICA');

INSERT INTO(SELECT * FROM REGIONES1) VALUES (6,'AUSTRALIA');

UPDATE (SELECT * FROM REGIONES1 WHERE REGION_ID > 3) SET REGION_NAME = LOWER(REGION_NAME);
